version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: composer
    steps:
      - checkout
      - run:
          command: |
            composer install
            ./lint.sh
            ./phpunit.sh
